### ISSUE TITLE
Allure report history trend vs Jenkins' allure history trend

### ISSUE THREAD

**Issue by hoopy728** [jenkinsci/allure-plugin#215] opened 2018-08-17 01:41 UTC
## Issue
The Allure report history trend colour is not the same as per Jenkins' Allure history trend. Is there any properties file that can configure the colour code type?

### Context
- **Jenkins version**: 2.7.8
- **Job type**: Maven

- **Allure plugin version**: 2.6.1
- **Allure commandline version**: -

### Problem description
Following are the history trend view via Allure report and Jenkins. As you can see the product defect is red in Allure report history but yellow in Jenkins history trend. I'm trying to sync the same colour toward Jenkins Allure history trend.

**Allure report's history trend**
![image](https://user-images.githubusercontent.com/37993078/44243109-e6759c80-a1ff-11e8-844c-4bbc4fc65cc7.png)

**Jenkins' Allure history trend**
![image](https://user-images.githubusercontent.com/37993078/44243140-1de44900-a200-11e8-9251-83bc26da6692.png)

**Comment by goatsy** [comment] 2019-02-12 11:38
Is there a fix for this behaviour?

**Comment by Agentbars** [comment] 2019-06-20 08:24
Will that be fixed?

Thanks)

**Comment by iridiculous** [comment] 2019-07-29 08:11
Can we get at least a comment here to know whether this gets fixed / if theres a workaround ? 
This is totally misleading

**Comment by abaradulkin** [comment] 2019-10-03 15:04
Vote for this issue!

**Comment by borbamartin** [comment] 2019-10-08 15:40
+1 failed tests are represented as broken in the Jenkins trend chart.

**Comment by iklimchuk** [comment] 2019-11-14 10:10
+1

**Comment by dwells-ancoris** [comment] 2020-01-13 11:28
Any update on this?

**Comment by timbi4** [comment] 2021-01-15 06:50
Failed tests are represented as broken in the Jenkins trend chart

**Comment by guzy0324** [comment] 2021-10-15 10:25
I encountered the same problem

**Comment by amdas383** [comment] 2022-08-18 06:25
Any update on this issue

**Comment by soul3510** [comment] 2023-01-04 14:24
I also encountered the same issue version 2.19.0

**Comment by cray2001** [comment] 2023-06-07 05:49
+1 the problem is not solved

**Comment by tony-it-world** [comment] 2023-09-25 10:50
+1. problem is actual. 2.24.0

**Closed** 2024-10-14 07:51 UTC
