### ISSUE TITLE
allure-results does not exists

### ISSUE THREAD

**Issue by kemuning** [jenkinsci/allure-plugin#201] opened 2018-03-07 08:54 UTC
## Issue
"allure-results does not exists" :

### Context
- **Jenkins version**: 2.89.4
- **Job type**: Freestyle

- **Allure plugin version**: 2.26.0
- **Allure commandline version**: 2.6.0

### Problem description

I know that other people have the same problem as mine and solve it, unfortunately I still couldn't find the answer to the problem "allure-results does not exists".

A snapshot of my pom.xml :
```xml
<build>
	<plugins>
		<plugin>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-maven</artifactId>
			<version>2.9</version>
		</plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.20.1</version>
			<configuration>
				<systemProperties>
					<property>
						<name>allure.results.directory</name>
						<value>${project.build.directory}/allure-results</value>
					</property>
				</systemProperties>
				<argLine>
					-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
				</argLine>
				<properties>
					<property>
						<name>listener</name>
						<value>io.qameta.allure.junit4.AllureJunit4</value>
					</property>
				</properties>
			</configuration>
			<dependencies>
				<dependency>
					<groupId>org.aspectj</groupId>
					<artifactId>aspectjweaver</artifactId>
					<version>${aspectj.version}</version>
				</dependency>
			</dependencies>
		</plugin>
	</plugins>
</build>
```

and a screenshot of Jenkins :

![capture_allurejenkins1](https://user-images.githubusercontent.com/23009699/37082635-576b2a6a-21ed-11e8-8726-9f067efcd594.PNG)

![capture_allurejenkins2](https://user-images.githubusercontent.com/23009699/37082650-5e6af57a-21ed-11e8-9b2f-e503ec4c9958.PNG)

### Logs & Traces

[EspaceClient] $ D:\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_2_6_0\bin\allure.bat generate -c -o D:\Jenkins\workspace\EspaceClient\allure-report
allure-results does not exists

**Comment by kemuning** [comment] 2018-03-07 14:31
Strange that no matter the Path I specified in the 'Results' (i.e. the above image), the Allure plugin just ignore it. I do believe it should be something like :

allure.bat generate <ResultsPath> -c -o xxx

Is this a bug ?

**Comment by premaram** [comment] 2018-03-07 22:41
@kemuning You are missing the Test-Results folder path for generate command.
Below is the format
<Allure.bat> generate <Your-Test-Results-Folder> -c -o <allure-report>

**Comment by kemuning** [comment] 2018-03-08 08:15
Where do you specify that Test-Result folder ? As my screenshot above, the test-result folder path was already specified, but Allure Commandline seems did not pick it up, hence : 

[EspaceClient] $ D:\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_2_6_0\bin\allure.bat generate -c -o D:\Jenkins\workspace\EspaceClient\allure-report
allure-results does not exists

**Comment by kemuning** [comment] 2018-03-09 08:23
Maybe I did not explain properly. According to Jenkins console log : 

```sh
[EspaceClient] $ D:\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure_2_6_0\bin\allure.bat generate -c -o D:\Jenkins\workspace\EspaceClient\allure-report
allure-results does not exists
````

despite I already specified the result path ( c.f. screen shot ).

Question is why the plugin ignore that path ?

**Comment by kemuning** [comment] 2018-03-09 13:50
This is so strange ...

If I remove the result path / do not specify the result path as shown below :

![capture_allurejenkins3](https://user-images.githubusercontent.com/23009699/37210383-da02e21c-23a8-11e8-971e-3a47b2e1b8a0.PNG)

I got an error :

```sh
[JENKINS] Archiving D:\Projets\eclipse-workspace\EC\fonctionelle\pom.xml to org.adie/espaceclient/0.0.1-SNAPSHOT/espaceclient-0.0.1-SNAPSHOT.pom
channel stopped

ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: The property 'Results' have to be specified! Check your job's configuration.
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:210)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
Finished: FAILURE
```

which is expected, I guess.


But when I specify that path :

![capture_allurejenkins4](https://user-images.githubusercontent.com/23009699/37210426-f97b4ff8-23a8-11e8-9fbe-516149fdabdf.PNG)

the plugin just ignore that path :

```sh
[JENKINS] Archiving D:\Projets\eclipse-workspace\EC\fonctionelle\pom.xml to org.adie/espaceclient/0.0.1-SNAPSHOT/espaceclient-0.0.1-SNAPSHOT.pom
channel stopped

[EspaceClient] $ D:\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure260\bin\allure.bat generate -c -o D:\Jenkins\workspace\EspaceClient\allure-report
allure-results does not exists

Report successfully generated to D:\Jenkins\workspace\EspaceClient\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Finished: SUCCESS
```


Is this anything wrong with how I configure in Jenkins the Allure plugin or my pom.xml ?

Thanks for your help.

**Comment by gavrilfb** [comment] 2018-03-10 13:46
@kemuning try _./allure-results_

**Comment by vbragin** [comment] 2018-03-12 13:39
@kemuning 

Am I right that you call mvn test on the project located on the path:
"D:\Projets\eclipse-workspace\EC\fonctionelle"
So the allure-results will be in:
"D:\Projets\eclipse-workspace\EC\fonctionelle\target\allure-results"?

From the above screenshot you can see the remark that "Path to Allure result have to be relevant to jenkins job workspace". Jenkins doesn't know anything about eclipse workspace.

Before execute the report generation you need to copy your allure-results
in to jenkins job workspace:
For example "D:\Jenkins\workspace\EspaceClient\target\allure-results"
then you can specify the Result Path like "target\allure-results"

**Closed** 2018-03-25 11:03 UTC

**Comment by kavalerchik** [comment] 2018-07-03 17:40
I had the same issue exactly, and I tried everything for a week!!. What I did eventually is added to the POM another allure-results (output) path to the job's workspace like that:

```
...
<systemProperties>
        <property>
              <name>allure.results.directory</name>
              <value>${project.build.directory}/allure-results</value>
        </property>
        <property>
              <name>allure.results.directory</name>
              <value>C:\Program Files (x86)\Jenkins\workspace\Suite_runner\allure-results</value>
        </property>
</systemProperties>
....
```

The second property is the path in the testing server. in my local pc I don't even have this path, and it works fine without errors (it doesn't create a new dir).

**Comment by xcorpio** [comment] 2018-10-23 12:00
![11301540295799_ pic_hd](https://user-images.githubusercontent.com/4575409/47358977-fdec6c80-d6fd-11e8-9f1f-9d4d39324953.jpg)

the path must be `target\allure-results`, can not be anything else custom directory

**Comment by lydialiu199403** [comment] 2018-12-10 05:10
@kemuning I have the same issue for weeks. Have you figured it out? I tried many paths, but always got the error
![image](https://user-images.githubusercontent.com/38413513/49711894-e866de00-fc7c-11e8-8e2b-20c6495e5d0b.png)
Thanks for your help.

**Comment by ahmedsalah0001** [comment] 2019-02-02 12:33
i have the same issue any help  ? that`s what appear when i try to see the results

C:\Users\Ahmed.Abouelsheikh>allure.bat serve allure-results
Generating report to temp directory...
allure-results does not exists
Report successfully generated to C:\Users\AHMED~1.ABO\AppData\Local\Temp\7765008883316529080\allure-report
Starting web server...
2019-02-02 14:23:17.910:INFO::main: Logging initialized @4313ms to org.eclipse.jetty.util.log.StdErrLog
Server started at <http://192.168.1.10:60744/>. Press <Ctrl+C> to exit

**Comment by kaverkiev** [comment] 2019-03-29 18:16
The same issue

**Comment by kaverkiev** [comment] 2019-03-29 18:16
Could you provide correct configutarion for Jenkins job for run test witn Allure ?

**Comment by dermotcanniffe** [comment] 2019-05-23 10:35
Wondering why this issue is closed - no fix or workaround was offered, it's not marked as a duplicate. No-one from the project responded.

**Comment by ukhare** [comment] 2019-06-07 13:13
Here is the solution:
Inside your work space (For me it is D:\m\Automation Project\Tests), Create a folder named "target" containing two subfolders "allure-results" and "allure-reports". 
2. In Post Build Actions of Jenkins Project provide these entries.
Results: target/allure-results
Report Path: target/allure-reports

Now run your tests and allure reports will be generated without any issues.

**Comment by dermotcanniffe** [comment] 2019-06-07 13:38
@ukhare - thank you for responding. Unfortunately that approach isn't sufficient. 
1. It should be possible to reference any subfolder, given the Allure plugin allows us to specify a folder location
2. To specify the path, it's *absolutely necessary* to use Ant-style globbing, e.g. **/myResultPath 
3. The plugin hint needs to reflect this
4. The tooltips are broken and need to be fixed, (I found the solution by grepping the tooltip html, which cannot be displayed from the plugin interface)

So, this is a defect, and needs to be addressed. 

See the following [reply on Issue #210](https://github.com/jenkinsci/allure-plugin/issues/210#issuecomment-495265855)

**Comment by ujjwalkhare11** [comment] 2019-06-07 14:11
@dermotcanniffe i agree that this a bug and needs a fix. My aim was just to help people with a temperory solution till you come up with a permanent fix. Keep the ball rolling

**Comment by dermotcanniffe** [comment] 2019-06-07 14:45
@ujjwalkhare11  oh I'm just a concerned citizen here, I'm not a project contributor. :)  Hopefully my root cause analysis will be of use to the project. 
Even so, just writing "target/allure-results" in the plugin won't actually work - it needs to be at least "**/target/allure-results" before the plugin will issue the correct syntax for the "allure" command.

**Comment by ujjwalkhare11** [comment] 2019-06-07 15:32
@dermotcanniffe what i mentioned is tested by myself. Let me try to explain you.
 1. 'target' is the folder/dir inside  workspace. 
2. 'allure-results' and 'allure-reports' are sub directories of 'target'.
3. As target is in workspace so no need to mention complete path here just mention 'target/allure-results' and 'target/allure-reports' will work fine. Allure pluging will find the exact path automatically. If you want more details here then you can check allure.bat or allure.sh file.
Eg. Following line in allure.bat file:

@REM find and validate allure home directory
if "%ALLURE_HOME%" == "" (
    set "ALLURE_HOME=%~dp0.."
)

if not exist "%ALLURE_HOME%\bin\allure.bat" (
    echo Invalid ALLURE_HOME: %ALLURE_HOME% is not a valid allure commandline directory >&2
    goto error
)

set "ALLURE_MAIN=ru.yandex.qatools.allure.CommandLine"
set "ALLURE_CP=%ALLURE_HOME%\lib\*;%ALLURE_HOME%\conf"
set "ALLURE_ARGS="

call :add_system_property_arg "allure.home" "%ALLURE_HOME%"
call :add_system_property_arg "allure.config" "%ALLURE_CONFIG%"
call :add_system_property_arg "allure.bundle.javaOpts" "%ALLURE_BUNDLE_JAVA_OPTS%"

"%JAVA%" %JAVA_ARGS% %ALLURE_ARGS% -cp "%ALLURE_CP%" %ALLURE_MAIN% %CMD_LINE_ARGS%

Its designed to accept path wrt to workspace path and find ALLURE_HOME. 

Same you can even see if delete mention allure results or allure reports path in jenkins and it will show error in red to set path e.g. target/allure-reports and target/allure-results.

All i am saying because i have tested this and it works.

Another thing i would like to tell you here is allure.bat is actually not able to identify allue-results even if mentioned in jenkins.
But if you pass allure-results path on CLI then it will work fine.

Adding on above if you provide default path of allure-results in allure.bat file like below then also it will work fine. 

"%JAVA%" %JAVA_ARGS% %ALLURE_ARGS% -cp "%ALLURE_CP%" %ALLURE_MAIN% %CMD_LINE_ARGS% D:\project\target\allure-results

But i did not provide this solution because it will limit to a common allure-results folder for all the projects.

Everything i have mentioned is tested and works.

**Comment by dermotcanniffe** [comment] 2019-06-07 16:14
@ujjwalkhare11 - it works for you because you're using Allure v1 which is deprecated. Allure v2 is broken such that specifying relative paths in the plugin causes the plugin to fail.

**Comment by ukhare** [comment] 2019-06-10 07:36
@dermotcanniffe<https://github.com/dermotcanniffe> I just checked and the plugin Im using has version 2.27.0<http://localhost:8080/pluginManager/plugin/allure-jenkins-plugin/thirdPartyLicenses>. Could you please suggest in which version I can reproduce the issue you talked about ?



Best Regards,
Ujjawal Khare
+91-7304658585
Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by dermotcanniffe** [comment] 2019-06-10 14:09
@ukhare - that's the plugin version. I was talking about the version of Allure the plugin uses. You can set it in Global Tool Configuration;
![image](https://user-images.githubusercontent.com/41295592/59201034-70c52d80-8b91-11e9-9368-23231070d94c.png)
Allure v1 appears to be more forgiving on malformed command line options. The plugin should be updated  to work properly with Allure v2, not the other way round.

**Comment by srotak5** [comment] 2019-06-10 18:24
as i see it there is still no fix for this problem ? i wasted a week trying to make it work

**Comment by amcanirn** [comment] 2019-06-11 09:12
I am also seeing this issue. Have tried the suggestions made above and nothing seems to work. Is there an older version of the plugin I can install to get this working?

**Comment by ukhare** [comment] 2019-06-11 09:33
Could you please share screenshots of your configuration ? Also share the version of allure plugin you are using.

Best Regards,
Ujjawal Khare
+91-7304658585
Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by srotak5** [comment] 2019-06-11 09:46
So guys after long fight i got some results:

The thing that helped me the most was the **./target/allure-results. 

I still can`t get trends and timeline working and i have no idea how to do that i`ve tried everything i found. So if you can help me please do so :)

I hope it helps and the version is 2.10.0 i think it`s the latest.

![Allure Report](https://user-images.githubusercontent.com/11695596/59261655-306fb900-8c3e-11e9-93e3-ffeccfaefeae.png)
![allure jenkins config](https://user-images.githubusercontent.com/11695596/59261657-31084f80-8c3e-11e9-8423-a97aa20c39b3.png)

**Comment by amcanirn** [comment] 2019-06-11 09:47
Allure Jenkins Plugin v 2.28.1
Allure Commandline v 2.12.1

![image](https://user-images.githubusercontent.com/51360049/59261843-15994680-8c36-11e9-9a91-70b11f35f2b9.png)

![image](https://user-images.githubusercontent.com/51360049/59261918-2cd83400-8c36-11e9-872d-132e5a1b4b56.png)

**Comment by amcanirn** [comment] 2019-06-11 10:20
@srotak5 I am still getting the same issue with **/target/allure-results. Did you have to change anything else?

**Comment by srotak5** [comment] 2019-06-11 10:52
@amcanirn not really :/

**Comment by dermotcanniffe** [comment] 2019-06-11 11:07
@amcanirn - I don't have a lot of experience with robot framework, but it's reporting that your results have been put into c:\Users\7476\Documents\RobotFramework (the "OUTPUT" line) , and not into any subdir relative to your jenkins job. So Allure isn't going to find anything in **/target , because **/target doesn't exist until it generates the report.

**Comment by dermotcanniffe** [comment] 2019-06-11 11:09
@srotak5 - do you retain historical artifacts from your jenkins builds? If jenkins is deleting previous artifacts, you won't get a history and a trend won't be generated.

**Comment by srotak5** [comment] 2019-06-11 11:11
@dermotcanniffe Yes i retain them, now i'm experimenting with copying old artifacts but it's still not working.

**Comment by dermotcanniffe** [comment] 2019-06-11 11:28
@srotak5 Hmmm. What happens if you go to your project's directory ( `/path/to/<workspace>/<project>` ) and run `allure serve <job>/target/allure-results` ?

**Comment by srotak5** [comment] 2019-06-11 11:40
@dermotcanniffe This 
![image](https://user-images.githubusercontent.com/11695596/59269090-792f6e00-8c4e-11e9-892e-d0d4625e40c4.png)

**Comment by amcanirn** [comment] 2019-06-11 11:52
@dermotcanniffe THANK YOU!  Updating the command to the below sorted me out. 

robot --listener allure_robotframework;%cd%\allure-results C:\Users\7476\Documents\RobotFramework\Web_Demo.robot

**Comment by dermotcanniffe** [comment] 2019-06-11 13:32
@srotak5 - when you look in `/path/to/<workspace>/<project>/allure-report/history` and look in history-trend.json - do the reportUrls work?  
Also, is the Jenkins url in the Config settings correct? 
![image](https://user-images.githubusercontent.com/41295592/59276087-89971700-8c55-11e9-9207-d7332063baf3.png)

**Comment by srotak5** [comment] 2019-06-12 04:48
@dermotcanniffe I think they are overwritten everytime i build even though im improting the as an artifact from previous build.
And yes Jenkins url is set up correctly.

**Comment by vitvitvit** [comment] 2019-06-26 11:48
The same error
Just reverted from allure cli 2.12.1 to 2.10.0 - now it works!

**Comment by dermotcanniffe** [comment] 2019-06-26 14:31
@vitvitvit you don't need to downgrade allure cli if you use ant-style globbing to define your results path.

**Comment by vitvitvit** [comment] 2019-06-28 10:28
@dermotcanniffe I tried to set it with "**/my_path" (as mentioned above), but it didn't help

**Comment by adityagautam** [comment] 2019-06-28 14:23
@dermotcanniffe It worked for me. Thanks for sharing the workaround.

**Comment by jijopjoy** [comment] 2019-07-08 10:48
@srotak5 : 

Hello Matus,

The screenshot you attached for allure report have 2 suites in it. how you are able to to that. I am running 3 suites but when each suite have same test, the report shows the result as Retries. Can you help me how you manage to add result of 2 execution in suite level

Regards,

Jijo

**Comment by srotak5** [comment] 2019-07-09 07:15
Hi @jijopjoy
I just made 2 Test suites in SoapUI(Calculation and Save) and each of them contains many testcases and thats it.  

If you want i can upload a screenshot or something 

Matus

**Comment by jijopjoy** [comment] 2019-07-09 07:29
Hi @srotak5 : Thank you for the reply !!
 
That would be great if you ask me. I have 3 different suites executing same set of test cases with different test data. In that case, what I get is one report with other two results as retires. I expect to get the results as 3 suites in a single report as what you shown in the screenshot. I am using TestNG adaptor. Can you help me in solving this?

Jijo

**Comment by srotak5** [comment] 2019-07-09 12:52
HI @jijopjoy 

Well i will try :D this is how it looks in my SoapUi first i've created request in wsdl's and then i've added them to testCases. The only problem i now have is that it's impossible to have one testCase with two steps where each step has different endpoint. Thas why one step is disabled at the moment.

![pic2](https://user-images.githubusercontent.com/11695596/60889205-d243ef00-a258-11e9-880a-3a81a6171e3e.PNG)
![pic1](https://user-images.githubusercontent.com/11695596/60889206-d243ef00-a258-11e9-8308-7a0c85da127f.PNG)

**Comment by YaoJie82** [comment] 2019-10-16 12:02
If you are writing code in java, the maven pom file
'''
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>2.12.0</version>
        </dependency>
'''
 should be the same as the allure plugin version under jenkins.
![image](https://user-images.githubusercontent.com/22559151/66917356-d057ac00-f04f-11e9-892d-770af7ab6eb1.png)

and set  plugin
![Uploading image.png…]()

**Comment by panyis** [comment] 2019-11-14 08:44
It works in this way:
1. Create a "allure-results" folder in your Jenkins work space
![image](https://user-images.githubusercontent.com/23692577/68839986-c2538480-06fc-11ea-9dcc-44c9fdb6dbb3.png)

2. Jenkins build configuration
![image](https://user-images.githubusercontent.com/23692577/68840167-1d857700-06fd-11ea-8a7e-3a5c56dc016d.png)

3. POM configuration
configure the allure.results.dirctory to Jenkins work space.
![image](https://user-images.githubusercontent.com/23692577/68840339-82d96800-06fd-11ea-9e02-da01c17de239.png)

4. result
it works.
![image](https://user-images.githubusercontent.com/23692577/68840546-e794c280-06fd-11ea-8d03-f566b1a51870.png)
![image](https://user-images.githubusercontent.com/23692577/68840570-f7140b80-06fd-11ea-8705-a2eee610a033.png)

**Comment by cronnoss** [comment] 2019-12-15 14:35
HI @panyis
Thanks! Your 4 screenshots really helped me!

**Comment by ashutosh3105** [comment] 2019-12-29 21:37
Easy solution would be either of below -

1. Reflect allure.properties file (/src/test/resources) and change value allure.results.directory = jenkins workspace  or pom.xml file > build > plugin > 
<groupId>io.qameta.allure</groupId>
  <artifactId>allure-maven</artifactId>
    <version>2.8</version>
    <configuration>
     **<propertiesFilePath>jenkins workspace location</propertiesFilePath>**
pom.xml file setting would be ignored if allure.properties file is present 
2. Go to Configure of your Job > General Tab > Advanced Button > Check the check box of "Use custom workspace" and give your current workspace 

second option would be usually super easy without doing anything if jenkins is hosted on local

**Comment by kchaitu4** [comment] 2020-01-07 17:00
How to configure allure for AWS Device Farm reports?

**Comment by YashkevichArtem** [comment] 2021-09-08 14:21
@panyis Thank you!!! You helped me with my problem.

**Comment by schwarzhere** [comment] 2024-05-09 04:48
Well another solution for those who facing "allure-results does not exist" despite the path in Post-build Actions:

Make sure that you have "allure-report" directory in
C:\ProgramData\Jenkins\.jenkins\workspace\{my_project_name}
