### ISSUE TITLE
Jenkins Failed to Read Test Results file hence failed to generate Allure Report

### ISSUE THREAD

**Issue by narasimhanukala** [jenkinsci/allure-plugin#306] opened 2022-02-06 13:57 UTC
### Context
- **Jenkins version**: 2.333
- **Job type**: Maven Project

- **Allure plugin version**: 2.30.1
- **Allure commandline version**: 2.10.0

### Problem description

Jenkins Failed to generate Allure Report as it is failed to read Allure test results xxxxx.json file
- I have successfully executed the Jenkins job , at the end of execution jenkins tried to collect the results file and and generate the allure report, but it failed to read the results json files.
- I would expect Jenkins to successfully read the .json files and generate report
- Due to which jenkins failed to show Allure report. refer to attached screenshot.

### Logs & Traces

Waiting for Jenkins to finish collecting data
[JENKINS] Archiving C:\Users\Administrator\.jenkins\workspace\TANGO_SMOKES\pom.xml to com.bambu/bambuGo_TangoUI/0.0.1-SNAPSHOT/bambuGo_TangoUI-0.0.1-SNAPSHOT.pom
Copying C:\Users\Administrator\.jenkins\workspace\TANGO_SMOKES@tmp\maven-reporters\moduleset to C:\Users\Administrator\.jenkins\jobs\TANGO_SMOKES

channel stopped

Unpacking https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.zip to C:\Users\Administrator\.jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure on Jenkins

[TANGO_SMOKES] $ C:\Users\Administrator\.jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure\bin\allure.bat generate C:\Users\Administrator\.jenkins\workspace\TANGO_SMOKES\target\allure-results -c -o C:\Users\Administrator\.jenkins\workspace\TANGO_SMOKES\allure-report

Could not read test result file C:\Users\Administrator\.jenkins\workspace\TANGO_SMOKES\target\allure-results\f95f6143-53d9-4635-bd7e-884adac71e2e-result.json
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "excluded" (class io.qameta.allure.model.Parameter), not marked as ignorable (2 known properties: "value", "name"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 2163] (through reference chain: io.qameta.allure.model.TestResult["steps"]->java.util.ArrayList[1]->io.qameta.allure.model.StepResult["parameters"]->java.util.ArrayList[0]->io.qameta.allure.model.Parameter["excluded"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at io.qameta.allure.allure2.Allure2Plugin.readTestResult(Allure2Plugin.java:344)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:104)
	at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
	at io.qameta.allure.Commands.generate(Commands.java:105)
	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/45284113/152684156-20db5a7c-a79a-4857-8e7a-cb00d107f9e0.png">

**Comment by narasimhanukala** [comment] 2022-02-06 13:59
my pom.xml contents as below:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.bambu</groupId>
  <artifactId>bambuGo_TangoUI</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>bambuGo_TangoUI</name>
<url>http://maven.apache.org</url>

 <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.7</maven.compiler.source>
		<maven.compiler.target>1.7</maven.compiler.target>
		<aspectj.version>1.9.5</aspectj.version>
		
		
		<skipTests>false</skipTests>
	</properties>

	 <dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.10.0</version>
		</dependency>

		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.4.0</version>
			<scope>compile</scope>
		</dependency>

		
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-testng</artifactId>
			<version>2.15.0</version>
		</dependency>
		
		<dependency>
		    <groupId>io.qameta.allure</groupId>
		    <artifactId>allure-java-migration</artifactId>
		    <version>2.17.2</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.141.59</version>
		</dependency>

		
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>4.1.2</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>4.1.2</version>
		</dependency>
		
		
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>

		
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>3.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>2.3.2</version>
		</dependency>

		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20200518</version>
		</dependency>

		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>3.0.0</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.6.1</version>
		</dependency>

		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.41</version>
		</dependency>
		
		
		<dependency>
			<groupId>postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.1-901-1.jdbc4</version>
		</dependency>
		<dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>javax.mail</artifactId>
			<version>1.6.2</version>
		</dependency>
		
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.0.4</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk</artifactId>
			<version>1.9.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-s3</artifactId>
			<version>1.11.371</version>
		</dependency>
		<dependency>
			<groupId>com.sun.jersey</groupId>
			<artifactId>jersey-client</artifactId>
			<version>1.8</version>
		</dependency>
		
		<dependency>
		    <groupId>org.jsoup</groupId>
		    <artifactId>jsoup</artifactId>
		    <version>1.14.3</version>
		</dependency>

	</dependencies>

	<build>
		<pluginManagement>
			<plugins>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.8.1</version>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.0.0-M5</version>
					<configuration>

						<suiteXmlFiles>
							
							<suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
						</suiteXmlFiles>
						<property>
							<name>listener</name>
							<value>com.Genaral.MyTestListenerAdapter</value>
						</property>

						
						
						

						<testFailureIgnore>true</testFailureIgnore>
						<argLine>
							-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
						</argLine>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.aspectj</groupId>
							<artifactId>aspectjweaver</artifactId>
							<version>${aspectj.version}</version>
						</dependency>
					</dependencies>
				</plugin>
				<plugin>
					<groupId>org.eclipse.jetty</groupId>
					<artifactId>jetty-maven-plugin</artifactId>
					<version>9.2.10.v20150310</version>
					<configuration>
						<webAppSourceDirectory>${project.build.directory}/site/allure-maven-plugin</webAppSourceDirectory>
						<stopKey>stop</stopKey>
						<stopPort>1234</stopPort>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<reporting>
		<excludeDefaults>true</excludeDefaults>
		<plugins>
			<plugin>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-maven</artifactId>
				<version>2.10.0</version>
				<configuration>
				<reportVersion>2.15.0</reportVersion>
				</configuration>
			</plugin>
		</plugins>
	</reporting>
</project>

**Comment by briankabuyesonos** [comment] 2022-03-18 16:02
I am having same error after implementing import io.qameta.allure.Param to hide sensitive data. 
Before that, Jenkins was able to read test results and generate an allure report.

**Comment by briankabuyesonos** [comment] 2022-08-02 17:00
I am getting similar error. @narasimhanukala did you ever resolve this ?

**Comment by Marc-93** [comment] 2022-08-03 07:50
any new on this issue?

**Comment by abbashassan-py** [comment] 2022-10-11 12:40
Any Fix for this issue? kindly help

> ## Issue
> ### Context
> * **Jenkins version**: 2.333
> * **Job type**: Maven Project
> * **Allure plugin version**: 2.30.1
> * **Allure commandline version**: 2.10.0
> 
> ### Problem description
> Jenkins Failed to generate Allure Report as it is failed to read Allure test results xxxxx.json file
> 
> * I have successfully executed the Jenkins job , at the end of execution jenkins tried to collect the results file and and generate the allure report, but it failed to read the results json files.
> * I would expect Jenkins to successfully read the .json files and generate report
> * Due to which jenkins failed to show Allure report. refer to attached screenshot.
> 
> ### Logs & Traces
> Waiting for Jenkins to finish collecting data [JENKINS] Archiving C:\Users\Administrator.jenkins\workspace\TANGO_SMOKES\pom.xml to com.bambu/bambuGo_TangoUI/0.0.1-SNAPSHOT/bambuGo_TangoUI-0.0.1-SNAPSHOT.pom Copying C:\Users\Administrator.jenkins\workspace\TANGO_SMOKES@tmp\maven-reporters\moduleset to C:\Users\Administrator.jenkins\jobs\TANGO_SMOKES
> 
> channel stopped
> 
> Unpacking https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.zip to C:\Users\Administrator.jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure on Jenkins
> 
> [TANGO_SMOKES] $ C:\Users\Administrator.jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\Allure\bin\allure.bat generate C:\Users\Administrator.jenkins\workspace\TANGO_SMOKES\target\allure-results -c -o C:\Users\Administrator.jenkins\workspace\TANGO_SMOKES\allure-report
> 
> Could not read test result file C:\Users\Administrator.jenkins\workspace\TANGO_SMOKES\target\allure-results\f95f6143-53d9-4635-bd7e-884adac71e2e-result.json com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "excluded" (class io.qameta.allure.model.Parameter), not marked as ignorable (2 known properties: "value", "name"]) at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 2163] (through reference chain: io.qameta.allure.model.TestResult["steps"]->java.util.ArrayList[1]->io.qameta.allure.model.StepResult["parameters"]->java.util.ArrayList[0]->io.qameta.allure.model.Parameter["excluded"]) at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823) at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153) at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567) at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294) at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070) at io.qameta.allure.allure2.Allure2Plugin.readTestResult(Allure2Plugin.java:344) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:104) at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47) at java.util.ArrayList.forEach(ArrayList.java:1257) at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69) at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58) at io.qameta.allure.Commands.generate(Commands.java:105) at io.qameta.allure.CommandLine.run(CommandLine.java:152) at java.util.Optional.orElseGet(Optional.java:267) at io.qameta.allure.CommandLine.main(CommandLine.java:88)
> 
> <img alt="image" width="1491" src="https://user-images.githubusercontent.com/45284113/152684156-20db5a7c-a79a-4857-8e7a-cb00d107f9e0.png">

Any Fix For This Issue?

**Comment by Shchepkin** [comment] 2023-06-15 17:11
the same issue

**Comment by nizarelhajri** [comment] 2023-06-21 14:54
I have the same issue, has anyone resolved this?

**Comment by jidey** [comment] 2023-07-31 10:16
also having this issue... Any solutions ?

**Comment by vivekvasu95** [comment] 2023-10-09 10:14
Kindly update the Allure commandline version: to latest

**Comment by KozyrevOleg** [comment] 2023-10-10 11:10
> Kindly update the Allure commandline version: to latest

Thank you! this really solves my problem. I didn't know that reportVersion has a different version

![image](https://github.com/jenkinsci/allure-plugin/assets/73142850/ec128e12-f743-46e8-9e11-8cc5f9b06340)

**Comment by qinian222** [comment] 2024-01-18 04:29
thanks,  solves my problem too

**Comment by i-maksudov** [comment] 2024-07-17 13:33
Hi!
I also faced this problem.
`Unrecognized field "excluded" (class io.qameta.allure.model.Parameter), not marked as ignorable (2 known properties: "value", "name"])`

I use the plugin for team city version [2.13.0](https://plugins.jetbrains.com/plugin/20544-allure-report/versions/stable)  - latest version on jetbrains marketplace


Please, tell me what the problem is and how to fix it?

**Comment by baev** [comment] 2024-07-17 14:55
The detailed explanation can be found at https://stackoverflow.com/a/78751733/3915166

> older Allure Commandline releases (before 2.16.0) had an error that would not let users generate a report from Allure Results with some unknown fields.

The solution is to upgrade to the latest Allure Commandline, which is 2.30.0 as of today.

**Closed** 2024-07-17 14:56 UTC
