### ISSUE TITLE
Jenkins Build Status

### ISSUE THREAD

**Issue by allustin** [jenkinsci/allure-plugin#24] opened 2015-10-01 16:37 UTC
In the Jenkins JUnit plugin there is a feature on after build step - set build status FAIL if there is failed steps

![2015-10-01 19-33-08](https://cloud.githubusercontent.com/assets/55323/10227071/fc6a9cb6-6873-11e5-942b-9e5ab275a75c.png)

In Allure plugin we need similar feature - change build status if in the report there is a failed scenario greater then <SomeFactor>

In the project we need this feature https://github.com/silverbulleters/vanessa-behavior/issues/82

**Comment by baev** [comment] 2017-05-28 12:15
duplicate of #13

**Closed by baev** 2017-05-28 12:15 UTC
